# ============================================================================
# Sophosic Platform Status Page Configuration - Upptime
# ============================================================================
# Documentation: https://upptime.js.org/docs/configuration
# Repository: https://github.com/ezpzzz/status
# Status Page: https://status.sophosic.ai
# ============================================================================

# ============================================================================
# REPOSITORY CONFIGURATION (REQUIRED)
# ============================================================================
owner: ezpzzz # GitHub username/organization
repo: status  # Repository name

# ============================================================================
# MONITORED SERVICES - Sophosic Platform
# ============================================================================
# All Sophosic services monitored with appropriate thresholds and health checks
# Check interval: Every 5 minutes (GitHub Actions minimum)
# ============================================================================

sites:
  # --------------------------------------------------------------------------
  # PRIMARY APPLICATION (app.sophosic.ai)
  # --------------------------------------------------------------------------
  # Main user-facing application frontend built with Next.js 15.5.6
  # Deployed on Render (ohio region) as web service
  - name: Sophosic App
    url: https://app.sophosic.ai/
    # Allow redirects and normal 200 responses
    expectedStatusCodes:
      - 200
      - 301
      - 302
    # 5 second threshold accounts for cold starts and asset loading
    maxResponseTime: 5000
    # Check page load, not just connectivity
    assignees:
      - ezpzzz

  # --------------------------------------------------------------------------
  # API BACKEND - HEALTH CHECK (api.sophosic.ai/ready)
  # --------------------------------------------------------------------------
  # RFC-compliant /ready endpoint for load balancer health checks
  # Lightweight check with no database queries
  - name: API Backend
    url: https://api.sophosic.ai/ready
    expectedStatusCodes:
      - 200
    # 3 second threshold for fast health check
    maxResponseTime: 3000
    # Check response body for unhealthy status
    __dangerous__body_down: '"status":"unhealthy"'
    __dangerous__body_down_if_text_missing: '"status"'
    assignees:
      - ezpzzz

  # --------------------------------------------------------------------------
  # API HEALTH - LIGHTWEIGHT PING (api.sophosic.ai/api/v2/health/ping)
  # --------------------------------------------------------------------------
  # Ultra-lightweight endpoint with minimal overhead
  # Returns simple status without dependency checks
  - name: API Health Check
    url: https://api.sophosic.ai/api/v2/health/ping
    expectedStatusCodes:
      - 200
    # 2 second threshold - should be very fast
    maxResponseTime: 2000
    # Validate response contains status field
    __dangerous__body_down: '"status":"degraded"'
    __dangerous__body_down_if_text_missing: '"status"'
    assignees:
      - ezpzzz

  # --------------------------------------------------------------------------
  # API COMPREHENSIVE HEALTH (api.sophosic.ai/api/v2/health/)
  # --------------------------------------------------------------------------
  # Full health check including database, Redis, circuit breaker status
  # Slower due to dependency checks but provides detailed diagnostics
  - name: API Detailed Health
    url: https://api.sophosic.ai/api/v2/health/
    expectedStatusCodes:
      - 200
    # 5 second threshold for comprehensive checks
    maxResponseTime: 5000
    # Check for unhealthy or degraded status
    __dangerous__body_down: '"status":"unhealthy"'
    assignees:
      - ezpzzz

  # --------------------------------------------------------------------------
  # DOCUMENTATION SITE (docs.sophosic.ai)
  # --------------------------------------------------------------------------
  # Platform documentation built with Nextra 4.6.0
  # Deployed on Render as web service (temporary workaround for Nextra bug)
  - name: Documentation
    url: https://docs.sophosic.ai/
    expectedStatusCodes:
      - 200
    # 4 second threshold for Nextra page load
    maxResponseTime: 4000
    assignees:
      - ezpzzz

  # --------------------------------------------------------------------------
  # MARKETING SITE (sophosic.ai)
  # --------------------------------------------------------------------------
  # Public marketing website built with Next.js
  # Deployed on Render (ohio region) as web service
  - name: Marketing Site
    url: https://sophosic.ai/
    expectedStatusCodes:
      - 200
      - 301
      - 302
    # 4 second threshold for marketing page load
    maxResponseTime: 4000
    assignees:
      - ezpzzz

# ============================================================================
# STATUS WEBSITE CONFIGURATION
# ============================================================================
# Public-facing status page settings with custom branding
# ============================================================================

status-website:
  # --------------------------------------------------------------------------
  # Custom Domain Configuration
  # --------------------------------------------------------------------------
  # CNAME record: status.sophosic.ai → ezpzzz.github.io
  # SSL: Auto-provisioned by GitHub Pages (Let's Encrypt)
  cname: status.sophosic.ai

  # --------------------------------------------------------------------------
  # Branding & Identity
  # --------------------------------------------------------------------------
  name: Sophosic Status
  logoUrl: https://sophosic.ai/logo.svg

  # --------------------------------------------------------------------------
  # Page Content
  # --------------------------------------------------------------------------
  introTitle: "**Sophosic Platform** Status"
  introMessage: |
    Real-time monitoring and status updates for all Sophosic services.

    All systems are monitored every 5 minutes. Subscribe below to receive instant notifications when incidents occur.

  # --------------------------------------------------------------------------
  # Navigation Links
  # --------------------------------------------------------------------------
  navbar:
    - title: Status
      href: /
    - title: Documentation
      href: https://docs.sophosic.ai
    - title: Sophosic
      href: https://sophosic.ai
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  # --------------------------------------------------------------------------
  # Theme Configuration
  # --------------------------------------------------------------------------
  # Options: light, dark, auto (respects user preference)
  theme: auto

  # --------------------------------------------------------------------------
  # SEO & Social Meta Tags
  # --------------------------------------------------------------------------
  metaTags:
    - name: "description"
      content: "Real-time status and uptime monitoring for Sophosic Platform services including App, API, Documentation, and Marketing sites."
    - name: "og:title"
      content: "Sophosic Platform Status"
    - name: "og:description"
      content: "Check the current operational status of all Sophosic services"
    - name: "og:image"
      content: "https://sophosic.ai/og-image.png"
    - name: "twitter:card"
      content: "summary_large_image"
    - name: "twitter:title"
      content: "Sophosic Platform Status"
    - name: "twitter:description"
      content: "Real-time status monitoring for Sophosic services"

# ============================================================================
# GITHUB ISSUES CONFIGURATION
# ============================================================================
# Auto-assign incidents to team members for rapid response
# ============================================================================

assignees:
  - ezpzzz
  # Add more team members:
  # - teammate1
  # - teammate2

# ============================================================================
# USER AGENT CONFIGURATION
# ============================================================================
# Identify Upptime monitoring requests in server logs
# ============================================================================

user-agent: sophosic-status-monitor

# ============================================================================
# INTERNATIONALIZATION (i18n)
# ============================================================================
# Customize status page text and labels
# ============================================================================

i18n:
  # Status indicators
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  incidentReport: Incident Report
  activeIncidentSummary: Opened $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentSubscribe: Subscribe to Updates
  incidentSubscribeText: Subscribe to receive email notifications
  incidentViewOnGitHub: View Details on GitHub

  # Status messages
  up: Operational
  down: Down
  degraded: Degraded

  # Response time
  ms: ms
  responseTime: Response Time
  responseTimeGraphAlt: Response time graph

  # Uptime periods
  uptime: Uptime
  uptimeDay: 24 hours
  uptimeWeek: 7 days
  uptimeMonth: 30 days
  uptimeYear: 1 year

  # Footer
  footer: |
    Powered by [Upptime](https://upptime.js.org) •
    [Sophosic Platform](https://sophosic.ai) •
    [Documentation](https://docs.sophosic.ai)

  # Live status
  liveStatus: Live Status
  overallUptime: Overall Uptime
  averageResponseTime: Average Response Time
  sevelDayResponseTime: 7-day Response Time

# ============================================================================
# NOTIFICATION CONFIGURATION (Optional)
# ============================================================================
# Uncomment and configure to enable real-time notifications
# Set webhook URLs as GitHub repository secrets
# ============================================================================

# notifications:
#   # Slack Integration
#   - type: slack
#     webhook: $SLACK_WEBHOOK_URL
#
#   # Discord Integration
#   - type: discord
#     webhook: $DISCORD_WEBHOOK_URL
#
#   # Telegram Integration
#   - type: telegram
#     botToken: $TELEGRAM_BOT_TOKEN
#     chatId: $TELEGRAM_CHAT_ID

# ============================================================================
# WORKFLOW SCHEDULE CONFIGURATION (Advanced)
# ============================================================================
# Default schedules work well for most use cases
# Only modify if you understand cron syntax and have specific requirements
# ============================================================================

# workflowSchedule:
#   graphs: "0 0 * * *"          # Generate graphs daily at midnight UTC
#   responseTime: "0 */6 * * *"  # Measure response time every 6 hours
#   staticSite: "0 1 * * *"      # Build status page daily at 1 AM UTC
#   summary: "0 0 * * *"         # Generate summary daily at midnight UTC
#   updateTemplate: "0 0 * * *"  # Check for template updates daily
#   updates: "0 3 * * *"         # Apply updates daily at 3 AM UTC
#   uptime: "*/5 * * * *"        # Monitor services every 5 minutes

# ============================================================================
# COMMIT MESSAGE CUSTOMIZATION (Optional)
# ============================================================================
# Customize automated commit messages for status updates
# ============================================================================

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"

# ============================================================================
# CONFIGURATION NOTES
# ============================================================================
#
# Response Time Thresholds Rationale:
# - App Frontend (5s): Accounts for cold starts, Next.js compilation, asset loading
# - API /ready (3s): Lightweight health check with no heavy operations
# - API /ping (2s): Ultra-lightweight, should return immediately
# - API /health (5s): Comprehensive check including database and Redis
# - Docs (4s): Nextra static site generation can take time
# - Marketing (4s): Next.js with dynamic content and API calls
#
# Health Check Body Validation:
# - __dangerous__body_down: Treats response as down if body contains this text
# - __dangerous__body_down_if_text_missing: Treats as down if text is missing
# - Used to catch "soft failures" where HTTP 200 returned but service is degraded
#
# Monitoring Frequency:
# - GitHub Actions minimum interval: 5 minutes
# - Adequate for SaaS monitoring (faster intervals increase false positives)
# - Balances detection speed with infrastructure load
#
# ============================================================================

# ============================================================================
# MAINTENANCE LOG
# ============================================================================
# 2025-11-02: Initial configuration created for Sophosic Platform
# - Added all 6 primary services (App, API x3, Docs, Marketing)
# - Configured custom domain: status.sophosic.ai
# - Set up health check body validation for API endpoints
# - Enabled issue auto-assignment to ezpzzz
# - Customized branding and i18n strings
# ============================================================================

# ============================================================================
# CUSTOM STYLING
# ============================================================================
# Professional branding matching sophosic.ai design system
# Typography: Geist Sans (loaded via custom CSS)
# Colors: Sophosic brand palette with dark mode support
# ============================================================================

# Custom scripts to inject Geist font and custom CSS
scripts:
  - src: "https://cdn.jsdelivr.net/npm/geist@1.2.0/dist/font.css"
    async: false

# Custom head HTML for additional styling
customHeadHtml: |
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/geist@1.2.0/dist/font.css">
  <style>
  /* Sophosic Brand Styling - Targets actual Upptime HTML structure */
  body{font-family:'Geist Sans',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif!important;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;font-feature-settings:"rlig" 1,"calt" 1}.container{max-width:1100px!important;padding:0 2.5rem!important}@media (max-width:768px){.container{padding:0 1.5rem!important}}nav{backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);padding:1.5rem 0!important;box-shadow:0 1px 3px rgba(0,0,0,0.05)!important}nav .container{display:flex;flex-direction:column;gap:1rem}nav .logo{display:flex;align-items:center;gap:0.75rem;font-size:1.25rem;font-weight:700;letter-spacing:-0.02em}nav .logo img{width:36px;height:36px;object-fit:contain}nav ul{display:flex;gap:0.25rem;margin:0;padding:0;list-style:none;flex-wrap:wrap}nav ul li{margin:0}nav ul li a{display:inline-block;padding:0.5rem 1rem;border-radius:0.75rem;font-size:0.875rem;font-weight:500;transition:all 0.2s cubic-bezier(0.16,1,0.3,1);text-decoration:none}nav ul li a:hover{transform:translateY(-1px);background:rgba(0,0,0,0.05)}@media (prefers-color-scheme:dark){nav ul li a:hover{background:rgba(255,255,255,0.08)}}@media (min-width:1024px){nav .container{flex-direction:row;justify-content:space-between;align-items:center}}header h1{font-size:2rem!important;font-weight:700!important;letter-spacing:-0.025em!important;line-height:1.1!important;margin-bottom:1rem!important}header p.lead{font-size:1rem!important;line-height:1.6!important;opacity:0.8;max-width:640px;margin:0 auto 3rem auto}@media (min-width:768px){header h1{font-size:2.75rem!important}header p.lead{font-size:1.125rem!important}}@media (min-width:1024px){header h1{font-size:3.5rem!important}header p.lead{font-size:1.25rem!important}}article{padding:2rem!important;margin-bottom:1.5rem!important;border-radius:1rem!important;border:1px solid rgba(0,0,0,0.08)!important;box-shadow:0 1px 3px rgba(0,0,0,0.04),0 2px 8px rgba(0,0,0,0.02)!important;transition:all 0.2s cubic-bezier(0.16,1,0.3,1)!important}article:hover{transform:translateY(-2px);box-shadow:0 4px 12px rgba(0,0,0,0.06),0 8px 24px rgba(0,0,0,0.04)!important;border-color:rgba(0,0,0,0.12)!important}@media (prefers-color-scheme:dark){article{border-color:rgba(255,255,255,0.1)!important;box-shadow:0 1px 3px rgba(0,0,0,0.2),0 2px 8px rgba(0,0,0,0.15)!important}article:hover{border-color:rgba(255,255,255,0.15)!important;box-shadow:0 4px 12px rgba(0,0,0,0.3),0 8px 24px rgba(0,0,0,0.2)!important}}article.up{border-left:4px solid #10B981!important}article.down{border-left:4px solid #EF4444!important}article.degraded{border-left:4px solid #F59E0B!important}.tag{padding:0.375rem 0.875rem!important;border-radius:9999px!important;font-size:0.8125rem!important;font-weight:600!important;letter-spacing:0.01em!important;display:inline-flex;align-items:center;gap:0.375rem}.tag.up::before,.tag.down::before,.tag.degraded::before{content:"";width:6px;height:6px;border-radius:50%;background:currentColor;display:inline-block}h2{font-size:1.5rem!important;font-weight:700!important;letter-spacing:-0.02em!important;margin-bottom:1.5rem!important}h3{font-size:1.125rem!important;font-weight:600!important;letter-spacing:-0.01em!important}h4{font-size:1rem!important;font-weight:600!important;margin-bottom:0.75rem!important}.f.changed form input[type="radio"]+label{padding:0.5rem 1rem;border-radius:0.75rem;font-size:0.875rem;font-weight:500;transition:all 0.2s ease;cursor:pointer}.f.changed form input[type="radio"]:checked+label{background:rgba(0,0,0,0.08);font-weight:600}@media (prefers-color-scheme:dark){.f.changed form input[type="radio"]:checked+label{background:rgba(255,255,255,0.12)}}article .graph{border-radius:0.75rem;overflow:hidden;margin-top:1rem}footer{padding:3rem 0!important;margin-top:4rem!important;font-size:0.875rem;opacity:0.7}footer a{font-weight:500;transition:opacity 0.2s ease}footer a:hover{opacity:0.8}.loading svg{opacity:0.4}@media (max-width:768px){article{padding:1.5rem!important}nav .logo{font-size:1.125rem}nav .logo img{width:32px;height:32px}}:focus-visible{outline:2px solid;outline-offset:2px;border-radius:0.5rem}@media (prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:0.01ms!important;animation-iteration-count:1!important;transition-duration:0.01ms!important}}
  </style>
